--MINI ERP
--USE MASTER
--DROP  DATABASE MINIERP
--GO
CREATE DATABASE MINIERP
GO
use MINIERP
--CADASTROS COMPLEMENTARES POR AREA
--CRIANDO TABELAS SEM DEPENDENCIAS/DEPENDENTES
--TABELAS UNIDADE FEDERAL
--DROP TABLE UF
CREATE TABLE UF
(
	COD_UF VARCHAR(2) NOT NULL PRIMARY KEY,
	NOME_UF VARCHAR(30) NOT NULL,
)
--TABELAS CIDADES

CREATE TABLE CIDADES
	(
	COD_CIDADE VARCHAR(7) NOT NULL PRIMARY KEY,
	COD_UF VARCHAR(2) NOT NULL,
	NOME_MUN VARCHAR(50) NOT NULL,
	CONSTRAINT FK_CID1 FOREIGN KEY (COD_UF) REFERENCES UF(COD_UF)
	)

--CRIANDO TABELAS CLIENTES
CREATE TABLE CLIENTES
	(
	ID_CLIENTE INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	RAZAO_CLIENTE VARCHAR(100)NOT NULL,
	FANTASIA VARCHAR(15) NOT NULL,
	ENDERECO VARCHAR(50) NOT NULL,
	NRO VARCHAR(10) NOT NULL,
	BAIRRO VARCHAR(20) NOT NULL,
	COD_CIDADE VARCHAR(7) NOT NULL,
	CEP VARCHAR(8),
	CNPJ_CPF VARCHAR(15),
	TIPO_CLIENTE NCHAR(1) CONSTRAINT CK_TC1 CHECK (TIPO_CLIENTE in ('F', 'J')),
	DATA_CADASTRO DATETIME NOT NULL,
	COD_PAGTO INT ,
	CONSTRAINT FK_CLI1 FOREIGN KEY (COD_CIDADE) 
	REFERENCES CIDADES(COD_CIDADE)
	)

--CRIACAO TABELA FORNECEDORES
CREATE TABLE FORNECEDORES
(
    ID_FOR INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	RAZAO_FORNEC VARCHAR(100)NOT NULL,
	FANTASIA VARCHAR(15) NOT NULL,
	ENDERECO VARCHAR(50) NOT NULL,
	NRO VARCHAR(10) NOT NULL,
	BAIRRO VARCHAR(20) NOT NULL,
	COD_CIDADE VARCHAR(7) NOT NULL,
	CEP VARCHAR(8),
	CNPJ_CPF VARCHAR(15),
	TIPO_FORNEC NCHAR(1) CONSTRAINT CK_TF1 CHECK (TIPO_FORNEC in ('F', 'J')),
	DATA_CADASTRO DATETIME NOT NULL,
	COD_PAGTO INT ,
	CONSTRAINT FK_FOR1 FOREIGN KEY (COD_CIDADE) 
	REFERENCES CIDADES(COD_CIDADE)
	)

--TABELAS TIPO DE MATERIAL
CREATE TABLE TIPO_MAT
	(
	COD_TIP_MAT INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	DESC_TIP_MAT VARCHAR(20) NOT NULL
	)
--CRIANDO TABELAS MATERIAL
CREATE TABLE MATERIAL
	(
	COD_MAT INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	DESCRICAO VARCHAR(50) NOT NULL,
	PRECO_UNIT DECIMAL(10,2) NOT NULL,
	COD_TIP_MAT INT NOT NULL,
	ID_FOR INT,
	CONSTRAINT FK_MAT1 FOREIGN KEY (COD_TIP_MAT) 
	REFERENCES TIPO_MAT(COD_TIP_MAT)
	)
--CRIANDO INDEX
CREATE INDEX IX_MAT ON MATERIAL(COD_TIP_MAT)

	
--PRODUCAO
CREATE TABLE ORDEM_PROD
	(
	ID_ORDEM INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	COD_MAT_PROD INT NOT NULL,
	QTD_PLAN DECIMAL(10,2) NOT NULL,
	QTD_PROD DECIMAL(10,2) NOT NULL,
	DATA_INI DATE,
	DATA_FIM DATE,
	SITUACAO CHAR(1),--A-ABERTA, P-PLANEJADA -F-FECHADA
    CONSTRAINT FK_OP1 FOREIGN KEY (COD_MAT_PROD) 
	REFERENCES MATERIAL(COD_MAT)
	)
--CRIACAO DE TABELAS APONTAMENTOS DE PRODUCAO
--DROP TABLE APONTAMENTOS
CREATE TABLE APONTAMENTOS
	(
	ID_APON INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	ID_ORDEM INT NOT NULL,
	COD_MAT_PROD INT,
	QTD_APON DECIMAL(10,2),
	DATA_APON DATETIME NOT NULL,
	--CAMPO LOTE CRIADO NO FINAL
	--LOGIN, SERA CRIADO APOIS CRIACAO DA TABELA USUARIOS
	CONSTRAINT FK_APON1 FOREIGN KEY (COD_MAT_PROD) 
	REFERENCES MATERIAL(COD_MAT),
	CONSTRAINT FK_APON2 FOREIGN KEY (ID_ORDEM) 
	REFERENCES ORDEM_PROD(ID_ORDEM)
	)

--CRIACAO DA TABELA FICHA TECNICA
CREATE TABLE FICHA_TECNICA
(
	ID_REF INT IDENTITY NOT NULL PRIMARY KEY,
	COD_MAT_PROD INT NOT NULL,
	COD_MAT_NECES INT NOT NULL,
	QTD_NECES DECIMAL(10,2) NOT NULL,
	CONSTRAINT FK_FIC1 FOREIGN KEY (COD_MAT_PROD) 
	REFERENCES MATERIAL(COD_MAT),
	CONSTRAINT FK_FIC2 FOREIGN KEY (COD_MAT_NECES) 
	REFERENCES MATERIAL(COD_MAT)
	)

--CRIACAO DA TABELA CONSUMO
--DROP TABLE CONSUMO
CREATE TABLE CONSUMO
(
	ID_APON INT NOT NULL,
	COD_MAT_NECES INT NOT NULL,
	QTD_CONSUMIDA DECIMAL(10,2) NOT NULL,
	LOTE VARCHAR(20) NOT NULL,
	CONSTRAINT FK_CONS1 FOREIGN KEY (COD_MAT_NECES) 
	REFERENCES MATERIAL(COD_MAT),
	CONSTRAINT FK_CONS2 FOREIGN KEY (ID_APON) 
	REFERENCES APONTAMENTOS(ID_APON)
	)


--SUPRIMENTOS
--CRIACAO DA TABELA 
CREATE TABLE ESTOQUE
	(
    COD_MAT INT NOT NULL PRIMARY KEY,
	QTD_SALDO DECIMAL(10,2) NOT NULL,
	CONSTRAINT FK_EST1 FOREIGN KEY (COD_MAT) 
	REFERENCES MATERIAL(COD_MAT)
	)
--DROP TABLE ESTOQUE_LOTE
--CRIACAO TABELAS ESTOQUE_LOTE
CREATE TABLE ESTOQUE_LOTE
	(
	COD_MAT INT NOT NULL,
	LOTE VARCHAR(20) NOT NULL,
	QTD_LOTE DECIMAL(10,2) NOT NULL,
	CONSTRAINT PK_ESTL1 PRIMARY KEY (COD_MAT,LOTE), --PK COMPOSTA
	CONSTRAINT FK_ESTL1 FOREIGN KEY (COD_MAT) 
	REFERENCES MATERIAL(COD_MAT)
	)
--CRIACAO TABELA MOV ESTOQUE
--DROP TABLE ESTOQUE_MOV
	CREATE TABLE ESTOQUE_MOV
	(
	ID_MOV INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TIP_MOV VARCHAR(1), --S=SAIDA ,E=ENTRADA
	COD_MAT INT NOT NULL,
	LOTE  VARCHAR(20) NOT NULL,
	QTD DECIMAL(10,2) NOT NULL,
	DATA_MOV DATE NOT NULL,
	DATA_HORA DATETIME NOT NULL,
	CONSTRAINT FK_ESTM1 FOREIGN KEY (COD_MAT) 
	REFERENCES MATERIAL(COD_MAT)
	--CAMPO LOGIN TABELA ESTOQUE_MOV CRIACAO APOS TABELA USUARIO
	)
--CRIACAO TABELAS PED_COMPRAS
--DROP TABLE PED_COMPRAS	
CREATE TABLE PED_COMPRAS
	(
	NUM_PEDIDO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	ID_FOR INT NOT NULL,
	COD_PAGTO INT NOT NULL, --ALTERAR  COD_PAGTO TAB PED_COMPRAS PARA FOREIGN KEY APOS TABELA COND_PAGTO  	
	DATA_PEDIDO DATE NOT NULL,
	DATA_ENTREGA DATE NOT NULL,
	SITUACAO NCHAR(1) NOT NULL,
	TOTAL_PED DECIMAL(10,2),
	CONSTRAINT FK_PEDC1 FOREIGN KEY (ID_FOR) 
	REFERENCES FORNECEDORES(ID_FOR)
	)
--CRIACAO DA TABELA PEDIDO COMPRAS
CREATE TABLE PED_COMPRAS_ITENS
	(
	NUM_PEDIDO INT NOT NULL,
	SEQ_MAT INT NOT NULL,
	COD_MAT INT NOT NULL,
	QTD     INT NOT NULL,
	VAL_UNIT DECIMAL(10,2) NOT NULL,
	CONSTRAINT FK_PEDIT1 FOREIGN KEY (NUM_PEDIDO) 
	REFERENCES PED_COMPRAS(NUM_PEDIDO),
	CONSTRAINT FK_PEDIT2 FOREIGN KEY (COD_MAT) 
	REFERENCES MATERIAL(COD_MAT),
	)
	

--RH
--CRIACAO TABELAS CENTRO DE CUSTO
CREATE TABLE CENTRO_CUSTO
	(
	COD_CC VARCHAR(4) NOT NULL PRIMARY KEY,
	NOME_CC VARCHAR(20) NOT NULL
	)

--CRIACAO TABELAS CARGOS
CREATE TABLE CARGOS 
	(COD_CARGO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	 NOME_CARGO VARCHAR(50)
	 )
--CRIACAO TABELA FUNCIONARIO
CREATE TABLE FUNCIONARIO 
	(
	MATRICULA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	COD_CC VARCHAR(4) NOT NULL,
	NOME   VARCHAR(50) NOT NULL,
	RG     VARCHAR(15) NOT NULL,
	CPF    VARCHAR(15) NOT NULL,
	ENDERECO  VARCHAR(50)NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	BAIRRO VARCHAR(50) NOT NULL,
	COD_CIDADE VARCHAR(7) NOT NULL,
	DATA_ADMISS DATE NOT NULL,
	DATE_DEMISS DATE,
	DATA_NASC DATE NOT NULL,
	TELEFONE VARCHAR(15) NOT NULL,
	COD_CARGO INT NOT NULL,
	CONSTRAINT FK_FUNC1 FOREIGN KEY (COD_CC) 
	REFERENCES CENTRO_CUSTO(COD_CC),
	CONSTRAINT FK_FUNC2 FOREIGN KEY (COD_CIDADE) 
	REFERENCES CIDADES(COD_CIDADE),
	CONSTRAINT FK_FUNC3 FOREIGN KEY (COD_CARGO) 
	REFERENCES CARGOS(COD_CARGO)
	)

--CRIACAO TABELA SALARIO
CREATE TABLE SALARIO
	(
	MATRICULA INT NOT NULL,
	SALARIO DECIMAL(10,2)NOT NULL,
	CONSTRAINT FK_SAL2 FOREIGN KEY (MATRICULA) 
	REFERENCES FUNCIONARIO(MATRICULA)
	)
--CRIACAO TABLE FOLHA DE PAGTO
--DROP TABLE FOLHA_PAGTO
CREATE TABLE FOLHA_PAGTO
	(
	MATRICULA INT NOT NULL,
	TIPO_PGTO CHAR(1) NOT NULL,-- (M-FOLHA,A-ADTO,F-FERIAS,D-13º,R-RESC),
	TIPO CHAR(1)  NOT NULL,--P=PROVENTOS D-DESCONTO
	EVENTO VARCHAR(30) NOT NULL, 
	MES_REF VARCHAR(2)NOT NULL,
	ANO_REF VARCHAR(4)NOT NULL,
	DATA_PAGTO DATE NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL,
    CONSTRAINT FK_FP1 FOREIGN KEY (MATRICULA) 
	REFERENCES FUNCIONARIO(MATRICULA)
	)

--SEGURANCA
--CRIACAO TA TABELAS USARIOS 
CREATE TABLE USUARIOS
	(
	LOGIN VARCHAR(30) NOT NULL PRIMARY KEY,
	MATRICULA INT NOT NULL,
	SENHA   VARCHAR(32) NOT NULL,
	SITUACAO CHAR(1) NOT NULL, --A=ATIVO -B BLOQUEADO
	CONSTRAINT FK_US1 FOREIGN KEY (MATRICULA) 
	REFERENCES FUNCIONARIO(MATRICULA)
	)


--FINANCEIRO
--CRIACAO TABELA CONTAS A RECEBER
CREATE TABLE CONTAS_RECEBER
	(
	ID_DOC INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
	ID_DOC_ORIG INT NOT NULL, --ALTER CAMPO ID_DOC_ORIG PARA FK TABELA NOTA_FISCAL
	PARC INT NOT NULL,
	DATA_VENC DATE NOT NULL,
	DATA_PAGTO DATE ,
	VALOR DECIMAL(10,2),
	CONSTRAINT FK_CR1 FOREIGN KEY (ID_CLIENTE) 
	REFERENCES CLIENTES(ID_CLIENTE)
	)

--CRIACAO TABELA CONTAS A PAGAR
--DROP TABLE CONTAS_PAGAR
CREATE TABLE CONTAS_PAGAR
	(
	ID_DOC INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_FOR INT NOT NULL,
	ID_DOC_ORIG INT NOT NULL, --ALTER CAMPO ID_DOC_ORIG PARA FK TABELA NOTA_FISCAL
	PARC INT NOT NULL,
	DATA_VENC DATE NOT NULL,
	DATA_PAGTO DATE ,
	VALOR DECIMAL(10,2),
	CONSTRAINT FK_CP1 FOREIGN KEY (ID_FOR) 
	REFERENCES FORNECEDORES(ID_FOR)
	)

--CRIACAO TABELA CONDIÇÕES DE PAGTO
CREATE TABLE COND_PAGTO
	(
	COD_PAGTO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOME_CP VARCHAR(50) NOT NULL ,
	)
--CRIACAO DA TABELAS DETALHES DE CONDICAO DE PAGTO COM PARCELA
CREATE TABLE COND_PAGTO_DET
	(
	COD_PAGTO INT NOT NULL,
	PARC     INT NOT NULL,
	DIAS     INT NOT NULL,
	PCT  DECIMAL(10,2)NOT NULL,--PERCENTUAL DA PARCELA
	CONSTRAINT FK_CONDP1 FOREIGN KEY (COD_PAGTO) 
	REFERENCES COND_PAGTO(COD_PAGTO)
	)

--COMERCIAL
--CRIACAO TABELA PEDIDO DE VENDAS
CREATE TABLE PED_VENDAS
	(
	NUM_PEDIDO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	ID_CLIENTE INT NOT NULL,
	COD_PAGTO INT NOT NULL, 
	DATA_PEDIDO DATE NOT NULL,
	DATA_ENTREGA DATE NOT NULL,
	SITUACAO NCHAR(1) NOT NULL, --A-ABERTO P-PLANEJADO -F FINALIZADO
	TOTAL_PED DECIMAL(10,2),
	CONSTRAINT FK_PV1 FOREIGN KEY (ID_CLIENTE) 
	REFERENCES CLIENTES(ID_CLIENTE),
	CONSTRAINT FK_PV2 FOREIGN KEY (COD_PAGTO) 
	REFERENCES COND_PAGTO(COD_PAGTO)
	)
--CRIACAO DA TABELA PEDIDO VENDAS ITENS
CREATE TABLE PED_VENDAS_ITENS
	(
	NUM_PEDIDO INT NOT NULL,
	SEQ_MAT INT NOT NULL,
	COD_MAT INT NOT NULL,
	QTD     INT NOT NULL,
	VAL_UNIT DECIMAL(10,2) NOT NULL,
	CONSTRAINT FK_PVIT1 FOREIGN KEY (NUM_PEDIDO) 
	REFERENCES PED_VENDAS(NUM_PEDIDO),
	)

--CRIACAO TABELAS VENDEDORES
--DROP TABLE VENDEDORES
CREATE TABLE VENDEDORES
    (ID_VEND INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	 MATRICULA INT NOT NULL
 	CONSTRAINT FK_VEND1 FOREIGN KEY (MATRICULA) 
	REFERENCES FUNCIONARIO(MATRICULA),
	 )
--CRIACAO DE TAB GERENTES DE VENDAS
CREATE TABLE GERENTES
    (ID_GER INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	 MATRICULA INT NOT NULL
 	CONSTRAINT FK_GER1 FOREIGN KEY (MATRICULA) 
	REFERENCES FUNCIONARIO(MATRICULA),
	 )
--CANAL DE VENDAS RELACIONA GERENTE COM VENDEDOR
CREATE TABLE CANAL_VENDAS_G_V
	(
	ID_GER INT NOT NULL,
	ID_VEND INT,
	CONSTRAINT FK_CGV1 FOREIGN KEY (ID_GER) 
	REFERENCES FUNCIONARIO(MATRICULA),
	CONSTRAINT FK_CGV2 FOREIGN KEY (ID_VEND) 
	REFERENCES FUNCIONARIO(MATRICULA),
	CONSTRAINT PK_CGV1 PRIMARY KEY (ID_GER,ID_VEND)
	)

--CANAL DE VENDAS RELACIONA VENDEDOR COM CLIENTE
CREATE TABLE CANAL_VENDAS_V_C
	(
	ID_VEND INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	CONSTRAINT FK_CVC1 FOREIGN KEY (ID_VEND) 
	REFERENCES FUNCIONARIO(MATRICULA),
	CONSTRAINT FK_CVC2 FOREIGN KEY (ID_CLIENTE) 
	REFERENCES CLIENTES(ID_CLIENTE)
	)
--CRIACAO DE TABELA PARA REGISTRA META DE VENDAS MES A MES/ANO
CREATE TABLE META_VENDAS
	(
	ID_VEND INT NOT NULL,
	ANO VARCHAR(4) NOT NULL,
	MES VARCHAR(2) NOT NULL,
	VALOR DECIMAL(10,2),
	CONSTRAINT FK_MV1 FOREIGN KEY (ID_VEND) 
	REFERENCES FUNCIONARIO(MATRICULA)
	)


--FISCAL
--CRIACAO DA TABELA DOS CODIGO DE OPERACOES FISCAIS
--DROP TABLE CFOP
	CREATE TABLE CFOP
	(
	COD_CFOP VARCHAR(5) NOT NULL PRIMARY KEY,
	DESC_CFOP VARCHAR(255) NOT NULL
	)
--CRIACAO DA TABELA NOTA_FISCAL
--DROP TABLE NOTA_FISCAL
--DROP TABLE NOTA_FISCAL_ITENS
CREATE TABLE NOTA_FISCAL
	(
	NUM_NF INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TIP_NF CHAR(1) NOT NULL, --E ENTRADA, S- SAIDA
	COD_CFOP VARCHAR(5) NOT NULL,
	ID_CLIFOR INT NOT NULL,
	COD_PAGTO INT NOT NULL, 
	DATA_EMISSAO DATETIME NOT NULL,
	DATA_ENTREGA DATE NOT NULL,
	TOTAL_NF DECIMAL(10,2),
	INTEGRADA_FIN CHAR(1) DEFAULT('N'),
	INTEGRADA_SUP CHAR(1) DEFAULT('N'),
	CONSTRAINT FK_NF1 FOREIGN KEY (COD_CFOP) 
	REFERENCES CFOP(COD_CFOP),
	CONSTRAINT FK_NF2 FOREIGN KEY (COD_PAGTO) 
	REFERENCES COND_PAGTO(COD_PAGTO)
	)
--CRIACAO DA TABELA NOTA_FISCAL_ITENS
CREATE TABLE NOTA_FISCAL_ITENS
	(
	NUM_NF INT NOT NULL,
	SEQ_MAT INT NOT NULL,
	COD_MAT INT NOT NULL,
	QTD     INT NOT NULL,
	VAL_UNIT DECIMAL(10,2) NOT NULL,
	PED_ORIG  INT NOT NULL,
	CONSTRAINT FK_NFIT1 FOREIGN KEY (NUM_NF) 
	REFERENCES NOTA_FISCAL(NUM_NF),
	CONSTRAINT FK_NFIT2 FOREIGN KEY (COD_MAT) 
	REFERENCES MATERIAL(COD_MAT),
	)	

--CRIACAO TABELAS PARAMETRO DE INSS

CREATE TABLE PARAM_INSS
(
 VIGENCIA_INI DATE,
 VIGENCIA_FIM DATE,
 VALOR_DE DECIMAL(10,2) NOT NULL,
 VALOR_ATE DECIMAL(10,2) NOT NULL,
 PCT DECIMAL(10,2) NOT NULL
 )

--CRIACAO DE TABELAS DE PARAMETRO DO IRRF
CREATE TABLE PARAM_IRRF
(
 VIGENCIA_INI DATE,
 VIGENCIA_FIM DATE,
 VALOR_DE DECIMAL(10,2) NOT NULL,
 VALOR_ATE DECIMAL(10,2) NOT NULL,
 PCT DECIMAL(10,2) NOT NULL,
 VAL_ISENT DECIMAL(10,2)
 )


 --CRIACAO TABELAS AUDIT SALARIO
 CREATE TABLE AUDITORIA_SALARIO
 (
	MATRICULA VARCHAR(30) NOT NULL,
	SAL_ANTES DECIMAL(10, 2) NOT NULL,
	SAL_DEPOIS DECIMAL(10, 2) NOT NULL,
	USUARIO VARCHAR(20) NOT NULL,
	DATA_ATUALIZCAO DATETIME NOT NULL
)

--ADD CAMPO LOGIN TABELA APONTAMENTOS CRIACAO APOS TABELA USUARIOS E FK
  ALTER TABLE APONTAMENTOS ADD LOGIN VARCHAR(30)NOT NULL;
  ALTER TABLE APONTAMENTOS ADD CONSTRAINT FK_APONT3
  FOREIGN KEY (LOGIN) REFERENCES USUARIOS(LOGIN);
  ALTER TABLE APONTAMENTOS ADD LOTE VARCHAR(20) NOT NULL
  --REMOVENDO CONSTRAINT PARA TESTE
  ALTER TABLE CONSUMO DROP CONSTRAINT  FK_CONS2
  ALTER TABLE APONTAMENTOS DROP CONSTRAINT  FK_APONT3

--ADD CAMPO LOGIN TABELA ESTOQUE_MOV  CRIACAO APOS TABELA USUARIO
  ALTER TABLE ESTOQUE_MOV ADD LOGIN VARCHAR(30)NOT NULL;
  ALTER TABLE ESTOQUE_MOV ADD CONSTRAINT FK_ESTM2
  FOREIGN KEY (LOGIN) REFERENCES USUARIOS(LOGIN);
 --REMOVENDO FK LOGIN PARA TESTES 
  ALTER TABLE ESTOQUE_MOV DROP CONSTRAINT  FK_ESTM2
 

--ALTERAR  COD_PAGTO TAB PED_COMPRAS PARA FOREIGN KEY APOS TABELA COND_PAGTO
  ALTER TABLE PED_COMPRAS ADD 
  FOREIGN KEY (COD_PAGTO) REFERENCES COND_PAGTO(COD_PAGTO);

--ALTER TABELA CONTAS_RECEBER CAMPO ID_DOC_ORIG PARA FK TABELA NOTA_FISCAL
  ALTER TABLE CONTAS_RECEBER ADD 
  FOREIGN KEY (ID_DOC_ORIG) REFERENCES NOTA_FISCAL(NUM_NF);
--ALTER TABELA CONTAS_PAGAR CAMPO ID_DOC_ORIG PARA FK TABELA NOTA_FISCAL
  ALTER TABLE CONTAS_PAGAR ADD 
  FOREIGN KEY (ID_DOC_ORIG) REFERENCES NOTA_FISCAL(NUM_NF);
