--PROCEDURE ORDEM_PROD
--SELECT * FROM PED_VENDAS
--SELECT * FROM PED_VENDAS_ITENS
--SELECT * FROM ORDEM_PROD
--MAT 1 QTD 35
--MAT 2 QTD 40
EXEC PROC_PLAN_ORDEM 12,2017 
--OBJETIVO GERAR ORDENS DE PRODUCAO DE ACORDO COM DEMANDA DE VENDAS
--DROP PROCEDURE PROC_PLAN_ORDEM
USE MINIERP
GO
CREATE PROCEDURE PROC_PLAN_ORDEM (@MES VARCHAR(2), 
                                  @ANO  VARCHAR(4)) 
AS 
 BEGIN 
    SET nocount ON 
	DECLARE @ErrorState INT;
 BEGIN TRANSACTION 
 --VERIFICANDO SE EXISTE PEDIDOS ABERTO PARA MES E ANO SELECIONADO
 IF (SELECT COUNT(*)
	FROM PED_VENDAS A
	INNER JOIN PED_VENDAS_ITENS B
	ON A.NUM_PEDIDO=B.NUM_PEDIDO
	WHERE A.SITUACAO='A'
	AND MONTH(A.DATA_ENTREGA)=@MES
    AND YEAR(A.DATA_ENTREGA)=@ANO)=0
	BEGIN 
		SET @ErrorState=1;
	END
	--
	
	ELSE 
    	BEGIN 
			INSERT INTO ORDEM_PROD 
			OUTPUT 'ORDEM PLANEJADA' MSG,INSERTED.ID_ORDEM ,INSERTED.COD_MAT_PROD
			SELECT B.COD_MAT,SUM(B.QTD) AS QTD_PLAN,0 QTD_PROD, 
			@ANO+'-'+@MES+'-01' AS DATA_INI,
			EOMONTH(@ANO+'-'+@MES+'-01') AS DATA_FIM,'A'
			FROM PED_VENDAS A
				INNER JOIN PED_VENDAS_ITENS B
				ON A.NUM_PEDIDO=B.NUM_PEDIDO
				WHERE A.SITUACAO='A' --APENAS PEDIDO EM ABERTO
				AND MONTH(A.DATA_ENTREGA)=@MES
				AND YEAR(A.DATA_ENTREGA)=@ANO
				GROUP BY B.COD_MAT;
		PRINT 'INSERT ORDEM PROD REALIZADO';
 
   UPDATE PED_VENDAS  SET SITUACAO='P'
   OUTPUT 'PEDIDO PLANEJADO' MSG,INSERTED.NUM_PEDIDO,DELETED.SITUACAO DE,INSERTED.SITUACAO PARA
   WHERE SITUACAO='A'
   AND MONTH(DATA_ENTREGA)=@MES
   AND YEAR(DATA_ENTREGA)=@ANO;
   
   PRINT 'PEDIDOS SITUACAO ATUALIZADA'; 
  END --FINAL ELSE 
 --TESTES FINAIS
    IF @ErrorState=1
		BEGIN
		 ROLLBACK
		 RAISERROR ('NAO EXISTEM MATERIAIS PARA PLANEJ. ORDEM', -- Message text.  
                      10, -- Severity.  
                      1 -- State.  
                      ); 
		  PRINT 'OPER. CANCELADA ROLLBACK';
        END
     ELSE IF @@ERROR <> 0
		BEGIN
		  ROLLBACK
		  PRINT 'OPERACAO CANCELADA'
		  PRINT @@error 
		END
		ELSE
		BEGIN
		      COMMIT  
		      PRINT 'OPERACAO REALIZADA COM SUCESSO';
     	END
	END 

--SELECT * FROM PED_VENDAS
--SELECT * FROM ORDEM_PROD 

