-- DROP TABLE CAD_MATERIAL
-- DROP TABLE NF_ITENS
CREATE TABLE CAD_MATERIAL
(
	cod_mat	INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nome_mat	VARCHAR(50) UNIQUE,
	saldo	INT NOT NULL DEFAULT 0
);

select * from CAD_MATERIAL;

INSERT INTO CAD_MATERIAL (NOME_MAT,SALDO) VALUES ('GAME',10);
INSERT INTO CAD_MATERIAL (NOME_MAT,SALDO) VALUES ('SMARTV 42',5);
INSERT INTO CAD_MATERIAL (NOME_MAT,SALDO) VALUES ('SMARTPHONE',15);
INSERT INTO CAD_MATERIAL (NOME_MAT,SALDO) VALUES ('NOTEBOOK',32);
INSERT INTO CAD_MATERIAL (NOME_MAT,SALDO) VALUES ('TABLET',50);

-- CRIANDO TABELA ITENS NOTA FISCAL
CREATE TABLE NF_ITENS
(	
	Venda		INT,
	cod_mat	INT,
	QTD	INT
);



-- TRIGGER ACAO DEPOIS DE INSERT NA TABELA NF ITENS
DELIMITER $
CREATE TRIGGER Tg_NF_ITENS_Insert AFTER INSERT
ON NF_ITENS
FOR EACH ROW
BEGIN
	UPDATE CAD_MATERIAL SET saldo = saldo - NEW.QTD
   WHERE cod_mat = NEW.cod_mat;
END$

-- TRIGGER ACAO DEPOIS DE DELETE NA TABELA NF ITENS
CREATE TRIGGER Tg_NF_ITENS_Delete AFTER DELETE
ON NF_ITENS
FOR EACH ROW
BEGIN
	UPDATE CAD_MATERIAL SET saldo = saldo + OLD.QTD
   WHERE cod_mat = OLD.cod_mat;
END$

-- TRIGGER ACAO DEPOIS DE UPDATE NA TABELA NF ITENS
CREATE TRIGGER Tg_NF_ITENS_update AFTER UPDATE
ON NF_ITENS
FOR EACH ROW
BEGIN
	UPDATE CAD_MATERIAL SET saldo = saldo +(OLD.QTD-NEW.QTD)
   WHERE cod_mat = OLD.cod_mat;
END$

DELIMITER ;

SHOW TRIGGERS;

-- VERIFICANDO DADOS 
SELECT * FROM CAD_MATERIAL;

-- INSERINDO VALORES
INSERT INTO NF_ITENS VALUES (1, 1,3);
INSERT INTO NF_ITENS VALUES (1, 2,1);
INSERT INTO NF_ITENS VALUES (1, 3,5);

-- UPDATE
UPDATE  NF_ITENS SET  QTD=4
WHERE VENDA='1' AND COD_MAT='1';

-- DELETE TESTE TRIGGER
DELETE FROM NF_ITENS 
	WHERE VENDA='1'
	AND COD_MAT='1';

-- VERIFICANDO DADOS
SELECT * FROM NF_ITENS
WHERE VENDA='1' AND COD_MAT='1'

/*
DROP TRIGGER Tg_NF_ITENS_Insert;
DROP TRIGGER Tg_NF_ITENS_Delete;
DROP TRIGGER Tg_NF_ITENS_uPDATE;
*/

