-- Parte 2 NEGA-REVOKE


-- NEGA Acesso DE ATUALIZACAO PARA ALUNO.
REVOKE UPDATE ON FUNCIONARIOS FROM 'ALUNO'@'localhost';

FLUSH PRIVILEGES;

-- Removendo Acesso DE UPDATE PARA ALUNO EM TODOS OBJETOS
REVOKE UPDATE  ON *.* FROM 'ALUNO'@'localhost';


-- Removendo Acesso DE DELETE PARA ALUNO.
REVOKE DELETE  ON FUNCIONARIOS FROM  'ALUNO'@'localhost';


-- Removendo Acesso DE DELETE PARA ALUNO EM TODOS OBJETOS
REVOKE DELETE  ON *.* FROM  'ALUNO'@'localhost';


-- Removendo Acesso DE INSERT PARA ALUNO.
REVOKE INSERT  ON FUNCIONARIOS FROM 'ALUNO'@'localhost';


-- Removendo Acesso DE SELECT  PARA ALUNO.
REVOKE SELECT ON FUNCIONARIOS FROM 'ALUNO'@'localhost';


-- Removendo Acesso DE SELECT e INSERT PARA ALUNO.
REVOKE SELECT, INSERT ON FUNCIONARIOS FROM 'ALUNO'@'localhost';


-- Removendo select com limitação de campos
REVOKE SELECT (NOME,SETOR) ON FUNCIONARIOS FROM  'ALUNO'@'localhost';


-- Removendo Acesso PARA EXCUTAR PROC proc_quadrado PARA ALUNO.
REVOKE EXECUTE ON PROCEDURE proc_quadrado FROM  'ALUNO'@'localhost';  


-- CONCENDENDO TODOS ACESSOS A TODOS OBJETOS
REVOKE ALL PRIVILEGES ON FUNCIONARIOS FROM  'ALUNO'@'localhost';


-- CONCENDENDO TODOS ACESSOS A TODOS OBJETOS
REVOKE ALL PRIVILEGES ON * . * FROM  'ALUNO'@'localhost';


-- RECARRAGANDO PREVILEGIOS
FLUSH PRIVILEGES;


select * from mysql.user where User='ALUNO';