-- CRIAR PROCEDIMENTO
DELIMITER //
CREATE PROCEDURE PROC_QTD_VAL (P_COD_MAT INT)
	BEGIN
		SELECT A.NOME,A.CUSTO,B.QTD,A.CUSTO*B.QTD TOTAL
        FROM MATERIAL A 
        INNER JOIN ESTOQUE B
        ON A.COD_MAT=B.COD_MAT
        WHERE A.COD_MAT=P_COD_MAT;
        SELECT 'CONSULTA REALIZADA COM SUCESSO' AS MSG;
END//
DELIMITER ;

CALL PROC_QTD_VAL(1);

-- DROP PROCEDURE PROC_QTD_VAL