--CREATE V_FCX
--ORIGEM 1 ENTRADA (PED VENDAS)

SELECT * FROM V_FCX
CREATE VIEW V_FCX
AS
SELECT '1. ENTRADA' TIPO_MOV ,
       'PROV. COMERCIAL' ORIGEM,
       A.NUM_PEDIDO,
	   A.ID_CLIENTE,
	   C.RAZAO_CLIENTE RAZAO ,
	   A.SITUACAO,
	   A.TOTAL_PED,
	   A.DATA_ENTREGA,
	   B.NOME_CP,
	   B.DIAS,
	   B.PARC,
	   DATEADD(DD,B.DIAS,A.DATA_ENTREGA) DATA_MOV,
	   A.TOTAL_PED/100*B.PCT TOT_PARC
   FROM F_PED_VENDAS A
   INNER JOIN D_COND_PAGTO B
    ON A.COD_PAGTO=B.COD_PAGTO
	INNER JOIN D_CLIENTES C
	ON A.ID_CLIENTE=C.ID_CLIENTE
     WHERE A.SITUACAO<>'F' --APENAS PEDIDOS NAO FATURADOS

	 UNION 
SELECT '2. SAIDAS',
      'PROV. SUPRIMENTOS' ORIGEM,
       A.NUM_PEDIDO,
	   A.ID_FOR,
	   C.RAZAO_FORNEC,
	   A.SITUACAO,
	   A.TOTAL_PED,
	   A.DATA_ENTREGA,
	   B.NOME_CP,
	   B.DIAS,
	   B.PARC,
	   DATEADD(DD,B.DIAS,A.DATA_ENTREGA) DATA_MOV,
	   A.TOTAL_PED/100*B.PCT TOT_PARC
   FROM F_PED_COMPRAS A
   INNER JOIN D_COND_PAGTO B
    ON A.COD_PAGTO=B.COD_PAGTO
	INNER JOIN D_FORNECEDORES C
	ON A.ID_FOR=C.ID_FOR
     WHERE A.SITUACAO<>'F' --APENAS PEDIDOS NAO ENTREGUES
UNION 
SELECT  '2. SAIDAS',
        'CONTAS A PAGAR' ORIGEM,
       A.ID_DOC,
	   A.ID_FOR,
	   C.RAZAO_FORNEC,
	   'A' SITUACAO,
	   A.VALOR,
	   A.DATA_VENC,
	   '' NOME_CP,
	   0 DIAS,
	   A.PARC,
	   A.DATA_VENC DATA_MOV,
	   A.VALOR TOT_PARC
   FROM F_CONTAS_PAGAR A
   INNER JOIN D_FORNECEDORES C
	ON A.ID_FOR=C.ID_FOR
     WHERE A.SITUACAO<>'PAGO'
 UNION       

SELECT '1. ENTRADA',
       'CONTAS A RECEBER'ORIGEM,
       A.ID_DOC,
	   A.ID_CLIENTE,
	   C.RAZAO_CLIENTE,
	   'A' SITUACAO,
	   A.VALOR,
	   A.DATA_VENC,
	   '' NOME_CP,
	   0 DIAS,
	   A.PARC,
	   A.DATA_VENC DATA_MOV,
	   A.VALOR TOT_PARC
   FROM F_CONTAS_RECEBER A
   INNER JOIN D_CLIENTES C
	ON A.ID_CLIENTE=C.ID_CLIENTE
     WHERE A.SITUACAO<>'PAGO'
